name: Precomp NIFs

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
      - ".github/workflows/precompiled-nifs.yml"
    tags:
      - "*"
  pull_request:
    paths:
      - ".github/workflows/precompiled-nifs.yml"
  workflow_dispatch:

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        nif: ["2.16", "2.17"]
        job:
          - { target: x86_64-apple-darwin, os: macos-13 }
          # Use native Apple Silicon runner for aarch64-apple-darwin to avoid cross-compilation issues
          - { target: aarch64-apple-darwin, os: macos-14 }
          - {
              target: aarch64-unknown-linux-gnu,
              os: ubuntu-22.04,
              use-cross: true,
            }
          - {
              target: aarch64-unknown-linux-musl,
              os: ubuntu-22.04,
              use-cross: true,
            }
          - { target: x86_64-pc-windows-gnu, os: windows-2022 }
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
          - { target: aarch64-pc-windows-msvc, os: windows-2022 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - {
              target: x86_64-unknown-linux-musl,
              os: ubuntu-22.04,
              use-cross: true,
            }
          - {
              target: riscv64gc-unknown-linux-gnu,
              os: ubuntu-22.04,
              use-cross: true,
            }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract project version
        shell: bash
        run: |
          version=$(grep -o '"[0-9][^"]*"' mix.exs | head -n1 | tr -d '"')
          echo "PROJECT_VERSION=$version" >> $GITHUB_ENV

      - name: Add target
        run: rustup target add ${{ matrix.job.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: native/dprint_markdown_formatter
          key: ${{ matrix.job.target }}-${{ matrix.nif }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: dprint_markdown_formatter
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross || false }}
          cross-version: ${{ matrix.job.cross-version || 'from-source' }}
          project-dir: native/dprint_markdown_formatter

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')

