name: Build precompiled NIFs

env:
  NIF_NAME: dprint_markdown_formatter
  NIF_DIRECTORY: native/dprint_markdown_formatter

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
      - ".github/workflows/release.yml"
    tags:
      - "*"

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.16", "2.17"]
        job:
          - { target: aarch64-apple-darwin, os: macos-12 }
          - {
              target: aarch64-unknown-linux-gnu,
              os: ubuntu-latest,
              use-cross: true,
            }
          - {
              target: aarch64-unknown-linux-musl,
              os: ubuntu-latest,
              use-cross: true,
            }
          - {
              target: riscv64gc-unknown-linux-gnu,
              os: ubuntu-latest,
              use-cross: true,
            }
          - { target: x86_64-apple-darwin, os: macos-12 }
          - { target: x86_64-pc-windows-gnu, os: windows-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - {
              target: x86_64-unknown-linux-musl,
              os: ubuntu-latest,
              use-cross: true,
            }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract project version
        shell: bash
        run: |
          version=$(grep -o '"[0-9][^"]*"' mix.exs | head -n1 | tr -d '"')
          echo "PROJECT_VERSION=$version" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: dprint_markdown_formatter
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross || false }}
          project-dir: ${{ env.NIF_DIRECTORY }}

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')
